protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'add', 'remove', 'settle'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView()
	{

		if (Yii::app()->request->isAjaxRequest) $this->layout = false;
		$this->render('view',array(
			'products'=>Order::model()->getOrderProducts( true ),
			'order'=> Order::model()->getOrder( true ),
			'model' => new Order(),
		));
	}

	/**
	 */
	public function actionSettle()
	{
		$order          = Order::model()->getOrder( true );
		$order['total'] = $this->getFormattedPrice( $order['total'] );
		$order['debug'] = $_SESSION;

		if(isset($_POST['Order']))
		{
			$model = new Order();
			$model->attributes = $_POST['Order'];

			if($model->save())
			{
				Yii::app()->user->setState( 'products', array() );// remove order products from session TODO uncomment
				echo CJSON::encode(
					array(
						'status' => 'success',
						'data' => $order
					)
				);
				Yii::app()->end();
			} else {
				echo CJSON::encode(
					array(
						'status' => 'error',
						'data'=>json_decode(CActiveForm::validate($model)),
					)
				);
			}
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionAdd($pid) {

		if ($product = Product::model()->exists("id=:id", array(':id'=>$pid))) {
			$cart = Yii::app()->user->getState( 'products', array() );
			$cart = array_merge( $cart, array( $pid ) );

			Yii::app()->user->setState( 'products', $cart);
			//if (Yii::app()->request->isAjaxRequest)
			{
				$order = Order::model()->getOrder(true);
				$order['total'] = $this->getFormattedPrice($order['total']);
				echo CJSON::encode(
					$order // unsettled order (not yet placed)
				);
			}
		} else {
			//TODO
			//throw new CHttpException('404');
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionRemove($pid) {
		$cart = Yii::app()->user->getState( 'products', array() );

		$pos = array_search($pid, $cart);
		if ( $pos !== false) {
			unset( $cart[ $pos ] );
			Yii::app()->user->setState( 'products', $cart );
		}

		//if (Yii::app()->request->isAjaxRequest)
		{
			$order = Order::model()->getOrder(true);
			$order['total'] = $this->getFormattedPrice($order['total']);
			echo CJSON::encode(
				$order // unsettled order (not yet placed)
			);
		}
	}




	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Order']))
		{
			$model->attributes=$_POST['Order'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->order_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Order');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Order('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Order']))
			$model->attributes=$_GET['Order'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Order the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Order::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Order $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='order-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent( '//layouts/main' ); ?>
<?php echo $content; ?>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php
/**
 * @var $this Controller
 */
$_img_base = Yii::app()->request->baseUrl .'/images/';
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="favicon.ico">

	<title><?php echo Yii::app()->name . (!empty($this->pageTitle) ? ' / '. CHtml::encode($this->pageTitle):''); ?></title>

	<!-- Bootstrap core CSS -->
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" rel="stylesheet">
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/ikeya.css" rel="stylesheet">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
<div id="bootloader"></div>
<div class="container">

	<div class="row">
		<div class="col-md-8 col-sm-6 col-xs-6 col-lg-offset-1">
			<?php echo CHtml::link( CHtml::image($_img_base . 'logo.png', Yii::app()->name, array('class'=>'logo')), Yii::app()->getBaseUrl(true) );?> <span class="header-phone dark-grey">+38 (097) <span class="red">778-17-78</span></span>
		</div>
		<div class="col-md-6 col-sm-8 col-xs-8 text-right header-cart">
			<a href="<?php echo Yii::app()->createUrl('order/view')?>" title="Заказ" class="js-cart-link"><span class="cart-count red"><?php echo $this->order['count']?></span><span class="skew-line dark-grey-bg"></span><sup class="price"><?php echo $this->order['total']?></sup></a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-16 col-lg-16 col-sm-16 col-xs-16" id="carousel-container">
			<div id="main-owl-carousel">
			<?php foreach ( Category::model()->findAll(array('order'=>'sort DESC')) as $category ) { ?>
				<img onclick="preLoadCategory('<?php echo 'category/'.$category->slug; ?>');" src="<?php echo $_img_base . $category->image; ?>">
				<?php //echo CHtml::image( $_img_base . $category->image, $category->name); ?>
				<?php// echo CHtml::link( CHtml::image( $_img_base . $category->image, $category->name), array('category/'.$category->slug), array('class'=>'category-link', 'title'=>CHtml::encode($category->name)) );?>
			<?php } ?>
			</div>


			<div class="ya-separator text-center col-md-10 col-md-offset-3 col-xs-12 col-xs-offset-2"><span></span></div>

		</div>
	</div>

<!--	CONTENT -->
	<div id="main-content">
		<?php echo $content; ?>
	</div>

<!--	END CONTENT -->

	<div class="ya-separator text-center col-md-10 col-md-offset-3 col-xs-12 col-xs-offset-2"><span></span></div>

	<div class="row footer">
		<div class="col-lg-offset-1 col-md-6 col-sm-6 col-xs-6 copyright">Copyright <?php echo date('Y');?></div>
		<div class="col-md-4 col-sm-4 col-xs-4 text-center"><?php echo CHtml::image(Yii::app()->getBaseUrl() . '/images/small_ikeya.png', 'ІКЕЯ');?></div>
		<div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 text-right"><a href="http://dmo1.net/"><?php echo Yii::t('app', 'сделано в DMO');?></a></div>
	</div>

<!--     POPUP -->
	<div id="popup" style="display: none">
		<div id="popup-content">
			<?php
			//$this->renderPartial('//product/view', array('model'=>Product::model()->findBySlug('stoly-privet-2')))
			?>
		</div>
		<a href="#" id="close-popup" class="orange-bg">
			&times;
			<span><?php echo Yii::t('app', 'Закрыть');?></span>
		</a>
	</div>
<!--     POPUP END // -->

<!--	ERROR -->
	<div id="error404" style="display: none">
		<?php $this->renderPartial('/site/error', array('code'=>'404'));?>
	</div>
<!--	ERROR END // -->

</div> <!-- /container -->
<script>
	var baseUrl = '<?php echo Yii::app()->getBaseUrl(true);?>/',
		siteTitle = '<?php echo str_replace("'", "\'", Yii::app()->name);?>',
		strings = {
			ru: {
				cat: '<?php echo str_replace("'", "\'", Yii::t('app', 'категория'));?>',
				prod: '<?php echo str_replace("'", "\'", Yii::t('app', 'товар'));?>',
				order: '<?php echo str_replace("'", "\'", Yii::t('app', 'Ваш заказ отправлен'));?>'
			}
		};


</script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery-1.11.1.min.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/owl.carousel.min.2.0.0.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.infinitescroll.min.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.history.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/iscroll.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/drag-on.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/app.js"></script>

</body>
</html>