protected/models/Order.php
<?php

/**
 * This is the model class for table "order".
 *
 * The followings are the available columns in table 'order':
 * @property integer $order_id
 * @property string $created
 * @property string $invoice_id
 */
class Order extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'order';
	}

	public function behaviors() {
		return array(
			'CTimestampBehavior' => array(
				'class'           => 'zii.behaviors.CTimestampBehavior',
				'createAttribute' => 'created',
				'updateAttribute' => 'updated',
			),
		);
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('fullname,email,phone,delivery_address', 'required'),

			array( 'fullname,email', 'length', 'max' => 255 ),

			array('email', 'email'),

			//array('invoice_id', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('order_id, created, invoice_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'products'     => array( self::HAS_MANY, 'OrderProduct', 'order_id' ),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		//TODO localize
		return array(
			'order_id' => 'Order',
			'fullname' => 'Имя и Фамилия',
			'delivery_address' => 'Адрес доставки',
			'phone' => 'Телефон',
			'created' => 'Created',
			'invoice_id' => 'Invoice',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('order_id',$this->order_id);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('invoice_id',$this->invoice_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Order the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


	/**
	 * @param $not_settled  if order is placed or not
	 * @return float
	 *
	 * If order is place then get producs total from order_product table
	 * otherwise from CWebUser state
	 */
	public function getOrder( $not_settled = true ){
		return ($not_settled) ? $this->_getUnsettledOrder() : $this->_getSettledOrder();
	}

	public function getOrderProducts( $not_settled = true ){
		return ($not_settled) ? $this->_getUnsettledOrderProducts() : $this->_getSettledOrderProducts();
	}

	public function _getSettledOrderProducts( ){
		$this->order_id = 1; //TODO remove this
		$products_ids = Yii::app()->db->createCommand("SELECT product_id FROM order_product WHERE order_id=:order_id")->queryAll(true, array(':order_id'=>$this->order_id));
		$_pids = array();

		if (!empty($products_ids)) {
			foreach ( $products_ids as $i => $pid ) {
				$_pids[ $i ] = (int) $pid['product_id'];
			}
		}

		return array(
			'counts'   => (array) array_count_values( $_pids ),
			'products' => (array) $this->_getProductsData( $_pids ),
		);

	}

	public function _getUnsettledOrderProducts( ){
		$products_ids = (array)Yii::app()->user->getState( 'products', array() );

		//if (!empty($products_ids)) {
		return array(
			'counts' => (array)array_count_values($products_ids),
			'products' => (array)$this->_getProductsData($products_ids)
		);
		//}
	}

	public function _getProductsData( $products_ids ){
		$pids = implode("','", $products_ids);
		return Yii::app()->db->createCommand("SELECT * FROM product WHERE id in ('$pids')")->queryAll(true);
	}

	private function _getUnsettledOrder(){
		$total = 0;
		$products_ids = Yii::app()->user->getState( 'products', array() );

		if (!empty($products_ids)) {
			$prices = $this->getProductsPrices($products_ids);

			foreach ( $products_ids as $pid ) {
				$total += $prices[$pid];
			}
		}
		return array(
			'total' => $total,
			'count' => count($products_ids),
		);
	}

	private function _getSettledOrder(){
		$this->order_id = 1; //TODO remove this
		$total = Yii::app()->db->createCommand("SELECT sum(price) as total, count(*) as count FROM order_product WHERE order_id=:order_id")->queryRow(true, array(':order_id'=>$this->order_id));
		return $total;
	}

	private function getProductsPrices($products_ids) {
		$result = array();

		foreach ( $products_ids as $i=>$pid ) {
			$products_ids[$i] = (int)$pid;
		}
		$pids = implode("','", $products_ids);

		$products = Yii::app()->db->createCommand("SELECT id, price FROM product WHERE id in ('$pids')")->queryAll(true);

		foreach ( $products as $product ) {
			$result[$product['id']] = $product['price'];
		}

		return $result;
	}

	public function afterSave(){
		$products = $this->_getUnsettledOrderProducts();
		foreach ( $products['products'] as $product ) {
			$order_product = new OrderProduct();
			$order_product->order_id = $this->order_id;
			$order_product->product_id = $product['id'];
			$order_product->product_name = $product['name'];
			$order_product->price = $product['price'];
			$order_product->quantity = (int)$products['counts'][$product['id']];
			$order_product->save();
		}
	}

}

protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'add', 'remove', 'settle'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView()
	{

		if (Yii::app()->request->isAjaxRequest) $this->layout = false;
		$this->render('view',array(
			'products'=>Order::model()->getOrderProducts( true ),
			'order'=> Order::model()->getOrder( true ),
			'model' => new Order(),
		));
	}

	/**
	 */
	public function actionSettle()
	{
		$order          = Order::model()->getOrder( true );
		$order['total'] = $this->getFormattedPrice( $order['total'] );
		$order['debug'] = $_SESSION;

		if(isset($_POST['Order']))
		{
			$model = new Order();
			$model->attributes = $_POST['Order'];

			if($model->save())
			{
				Yii::app()->user->setState( 'products', array() );// remove order products from session TODO uncomment
				echo CJSON::encode(
					array(
						'status' => 'success',
						'data' => $order
					)
				);
				Yii::app()->end();
			} else {
				echo CJSON::encode(
					array(
						'status' => 'error',
						'data'=>json_decode(CActiveForm::validate($model)),
					)
				);
			}
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionAdd($pid) {

		if ($product = Product::model()->exists("id=:id", array(':id'=>$pid))) {
			$cart = Yii::app()->user->getState( 'products', array() );
			$cart = array_merge( $cart, array( $pid ) );

			Yii::app()->user->setState( 'products', $cart);
			//if (Yii::app()->request->isAjaxRequest)
			{
				$order = Order::model()->getOrder(true);
				$order['total'] = $this->getFormattedPrice($order['total']);
				echo CJSON::encode(
					$order // unsettled order (not yet placed)
				);
			}
		} else {
			//TODO
			//throw new CHttpException('404');
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionRemove($pid) {
		$cart = Yii::app()->user->getState( 'products', array() );

		$pos = array_search($pid, $cart);
		if ( $pos !== false) {
			unset( $cart[ $pos ] );
			Yii::app()->user->setState( 'products', $cart );
		}

		//if (Yii::app()->request->isAjaxRequest)
		{
			$order = Order::model()->getOrder(true);
			$order['total'] = $this->getFormattedPrice($order['total']);
			echo CJSON::encode(
				$order // unsettled order (not yet placed)
			);
		}
	}




	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Order']))
		{
			$model->attributes=$_POST['Order'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->order_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Order');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Order('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Order']))
			$model->attributes=$_GET['Order'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Order the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Order::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Order $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='order-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/order/_form.php
<?php
/* @var $this OrderController */
/* @var $model Order */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'order-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
		<?php echo $form->error($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'invoice_id'); ?>
		<?php echo $form->textField($model,'invoice_id',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'invoice_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/order/_search.php
<?php
/* @var $this OrderController */
/* @var $model Order */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'order_id'); ?>
		<?php echo $form->textField($model,'order_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'invoice_id'); ?>
		<?php echo $form->textField($model,'invoice_id',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/order/_view.php
<?php
/* @var $this OrderController */
/* @var $data Order */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('order_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->order_id), array('view', 'id'=>$data->order_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created')); ?>:</b>
	<?php echo CHtml::encode($data->created); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('invoice_id')); ?>:</b>
	<?php echo CHtml::encode($data->invoice_id); ?>
	<br />


</div>

protected/views/order/admin.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Create Order', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#order-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Orders</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'order-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'order_id',
		'created',
		'invoice_id',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/order/create.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>Create Order</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/order/index.php
<?php
/* @var $this OrderController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Orders',
);

$this->menu=array(
	array('label'=>'Create Order', 'url'=>array('create')),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>Orders</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/order/update.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	$model->order_id=>array('view','id'=>$model->order_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Create Order', 'url'=>array('create')),
	array('label'=>'View Order', 'url'=>array('view', 'id'=>$model->order_id)),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>Update Order <?php echo $model->order_id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/order/view.php
<?php
/**
 * @var $this OrderController
 * @var $order array
 * @var $model Order
 */
?>
<?php
function _drawErrorMessage($model, $attribute) {
	return sprintf('<div id="%s_em_" class="error">&nbsp;</div>', CHtml::activeId($model, $attribute));
}
?>
<div class="cart-view">
	<div class="row">
		<div class="col-md-16 order-header">
			<h1 class="">Заказ</h1>
		</div>
	</div>
	<?php if (!empty($products['products'])) { ?>

	<div class="row">
		<div class="col-md-8 col-sm-16 col-xs-16 order-content text-center">
			<table>
				<?php
				foreach ( $products['products'] as $i => $product ) {
					?>
					<tr>
						<td><?php echo $product['name']?></td>
						<td class="price">
							<?php echo $products['counts'][$product['id']];?> <em>&times;</em> <?php echo $this->getFormattedPrice($product['price'])?> / <?php echo CHtml::link( Yii::t('app', 'Удалить'), array('order/remove', 'pid'=>$product['id']), array('class'=>'order-remove') );?>
						</td>
					</tr>
				<?php } ?>
				<tr class="last">
					<td class="text-right">Итого:</td>
					<td class="price"><?php echo $this->getFormattedPrice($order['total']);?></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-16 col-sm-16 col-xs-16">
			<form role="form" id="order-form" class="order-form">
				<?php
				echo CHtml::activeTextField($model, 'fullname', array( 'placeholder'=>"Имя и Фамилия"));
				echo _drawErrorMessage($model, 'fullname');
				?>


				<?php
				echo CHtml::activeTextField($model, 'email', array( 'placeholder'=>"Email"));
				echo _drawErrorMessage($model, 'email');
				?>


				<?php
				echo CHtml::activeTextField($model, 'phone', array( 'placeholder'=>"Телефон: (098)555-55-55"));
				echo _drawErrorMessage($model, 'phone');
				?>


				<?php
				echo CHtml::activeTextArea($model, 'delivery_address', array( 'placeholder'=>"Адрес доставки: город, улица, дом/квартира"));
				echo _drawErrorMessage($model, 'delivery_address');
				?>

			</form>
		<div>
	</div>
	<div class="row">
		<div class="col-md-16">
			<?php echo CHtml::link(Yii::t('app', 'Отправить заказ'), array('order/settle'), array('class'=>'btn btn-primary btn-lg js-settle-order'));?>
		</div>
	</div>
	<?php } else { ?>
	<div class="row">
		<div class="col-md-16 col-sm-16 text-center"><?php echo Yii::t('app', 'Вы не выбрали ниодного товара');?></div>
	</div>
	<?php } ?>
</div>