protected/models/Category.php
<?php

/**
 * This is the model class for table "category".
 *
 * The followings are the available columns in table 'category':
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $created
 * @property string $updated
 *
 * The followings are the available model relations:
 * @property Product $products
 */
class Category extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'category';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, slug, created, updated', 'required'),
			array('name', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, slug, created, updated', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'products' => array(self::HAS_MANY, 'Product', 'category_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'slug' => 'Slug',
			'created' => 'Created',
			'updated' => 'Updated',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('slug',$this->slug,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('updated',$this->updated,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Category the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function findBySlug($slug) {
		return $this->find('slug=:slug', array(':slug'=>$slug));
	}
}

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request

			/*array(
				'COutputCache + view',
				'duration'=>3600,
				'cacheID' => 'cache',
				'varyByParam'=>array('slug', 'Product_page'),
			),*/
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'error'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Category;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		if (Yii::app()->request->isAjaxRequest) $this->layout = false;

		$hitsProducts = Product::getHitProduct();

		$newProducts = Product::getNewProduct();

		$this->render('index',array(
			'hitsProducts'=>$hitsProducts,
			'newProducts'=>$newProducts,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionView($slug='')
	{
		if (Yii::app()->request->isAjaxRequest) $this->layout = false;

		$category = Category::model()->findBySlug($slug);
		$this->render('view',array(
			'model'=>$category,
			'dataProvider'=>Product::model()->getCategoryProducts($category->id),
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Category('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Category']))
			$model->attributes=$_GET['Category'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Category the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Category::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Category $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			$this->{(Yii::app()->request->isAjaxRequest)?'renderPartial':'render'}('/site/error',
				array(
					'code'          => $error['code'],
					'message'       => $error['message'],
					'message_title' => Yii::t( 'app', 'Не найдено' )
				)
			);
		}
	}
}

protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'add', 'remove', 'settle'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView()
	{

		if (Yii::app()->request->isAjaxRequest) $this->layout = false;
		$this->render('view',array(
			'products'=>Order::model()->getOrderProducts( true ),
			'order'=> Order::model()->getOrder( true ),
			'model' => new Order(),
		));
	}

	/**
	 */
	public function actionSettle()
	{
		$order          = Order::model()->getOrder( true );
		$order['total'] = $this->getFormattedPrice( $order['total'] );
		$order['debug'] = $_SESSION;

		if(isset($_POST['Order']))
		{
			$model = new Order();
			$model->attributes = $_POST['Order'];

			if($model->save())
			{
				Yii::app()->user->setState( 'products', array() );// remove order products from session TODO uncomment
				echo CJSON::encode(
					array(
						'status' => 'success',
						'data' => $order
					)
				);
				Yii::app()->end();
			} else {
				echo CJSON::encode(
					array(
						'status' => 'error',
						'data'=>json_decode(CActiveForm::validate($model)),
					)
				);
			}
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionAdd($pid) {

		if ($product = Product::model()->exists("id=:id", array(':id'=>$pid))) {
			$cart = Yii::app()->user->getState( 'products', array() );
			$cart = array_merge( $cart, array( $pid ) );

			Yii::app()->user->setState( 'products', $cart);
			//if (Yii::app()->request->isAjaxRequest)
			{
				$order = Order::model()->getOrder(true);
				$order['total'] = $this->getFormattedPrice($order['total']);
				echo CJSON::encode(
					$order // unsettled order (not yet placed)
				);
			}
		} else {
			//TODO
			//throw new CHttpException('404');
		}
	}

	/**
	 * Adds product to an order.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $pid the ID of the product to be added
	 * @throws CHttpException
	 */
	public function actionRemove($pid) {
		$cart = Yii::app()->user->getState( 'products', array() );

		$pos = array_search($pid, $cart);
		if ( $pos !== false) {
			unset( $cart[ $pos ] );
			Yii::app()->user->setState( 'products', $cart );
		}

		//if (Yii::app()->request->isAjaxRequest)
		{
			$order = Order::model()->getOrder(true);
			$order['total'] = $this->getFormattedPrice($order['total']);
			echo CJSON::encode(
				$order // unsettled order (not yet placed)
			);
		}
	}




	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Order']))
		{
			$model->attributes=$_POST['Order'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->order_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Order');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Order('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Order']))
			$model->attributes=$_GET['Order'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Order the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Order::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Order $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='order-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/category/_form.php
<?php
/* @var $this CategoryController */
/* @var $model Category */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'category-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'slug'); ?>
		<?php echo $form->textArea($model,'slug',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'slug'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'image'); ?>
		<?php echo $form->textField($model,'image',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'image'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'sort'); ?>
		<?php echo $form->textField($model,'sort'); ?>
		<?php echo $form->error($model,'sort'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
		<?php echo $form->error($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'updated'); ?>
		<?php echo $form->textField($model,'updated'); ?>
		<?php echo $form->error($model,'updated'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/category/_hits.php
<?php
/**
 * @var $this CategoryController
 * @var array $hitsProducts
 */
?>
<!-- HITS -->
<!-- row END // -->
<div class="row hits">
	<div class="col-md-4 vmiddle col-md-offset-2 col-md-offset-2 col-sm-offset-1  col-sm-5 col-xs-16">
		<?php echo CHtml::image(Yii::app()->getBaseUrl(true). '/images/hit_products.png', Yii::t('app', 'Хиты продаж'), array('class'=>'img-responsive')) . "\n";?>
	</div>
<?php
$i = 1;
foreach ( $hitsProducts as $product ) {
	if ($i % 3 == 0) {
		echo " <!-- row --> \n".
		     '<div class="row hits">' . "\n";
	}

	echo '  <div class="vmiddle col-md-4 ' . ( ( $i % 3 == 0 ) ? 'col-md-offset-2 col-sm-offset-1' : '' ) . ' col-sm-5 col-xs-16">' . "\n";
	// echo '  <div class="col-md-4 vmiddle product-lll '.(($i % 3 == 0)?'col-md-offset-2':'').'">'. "\n";
	$this->renderPartial('_product', array('data'=>$product));
	echo '  </div>' . "\n";

	$i++;
	if ($i % 3 == 0 || $i == count($hitsProducts)+1) {
		echo "</div>\n<!-- row END // -->\n\n";
	}
}
?>

<!-- HITS END // -->

protected/views/category/_new.php
<?php
/**
 * @var $this CategoryController
 * @var array $newProducts
 */
?>
<!-- HITS -->
<!-- row END // -->
<div class="row hits">
	<div class="col-md-4 vmiddle col-md-offset-2 col-md-offset-2 col-sm-offset-1  col-sm-5 col-xs-16">
		<?php echo CHtml::image(Yii::app()->getBaseUrl(true). '/images/new_products.png', Yii::t('app', 'Новинки'), array('class'=>'img-responsive')) . "\n";?>
	</div>
	<?php
	$i = 1;
	foreach ( $newProducts as $product ) {
		if ($i % 3 == 0) {
			echo " <!-- row --> \n".
			     '<div class="row hits">' . "\n";
		}

		echo '  <div class="vmiddle col-md-4 ' . ( ( $i % 3 == 0 ) ? 'col-md-offset-2 col-sm-offset-1' : '' ) . ' col-sm-5 col-xs-16">' . "\n";
		// echo '  <div class="col-md-4 vmiddle product-lll '.(($i % 3 == 0)?'col-md-offset-2':'').'">'. "\n";
		$this->renderPartial('_product', array('data'=>$product));
		echo '  </div>' . "\n";

		$i++;
		if ($i % 3 == 0 || $i == count($newProducts)+1) {
			echo "</div>\n<!-- row END // -->\n\n";
		}
	}
	?>

	<!-- HITS END // -->

protected/views/category/_product.php
<?php
/**
 * @var $this CategoryController
 * @var $data Product
 */
?>
	<!-- PRODUCT -->
	<div class="product-item<?php echo (count($data->productProperties) > 0)?'':' noprops'; //if ($data->id == 8) echo ' expanded';//DEBUG ?>">
		<a href="<?php echo Yii::app()->createUrl('product/'.$data->slug)?>" title="<?php echo CHtml::encode($data->name);?>">
		<img src="<?php echo Yii::app()->getBaseUrl().'/images/products/'.$data->image?>" class="img-responsive" alt="<?php echo CHtml::encode($data->name);?>">
		<p>
			<span class="name">
				<?php echo CHtml::encode($data->name);?>
				<em class="clearfix"><?php echo CHtml::encode($data->type);?></em>
			</span>
			<span class="skew-line x2 dark-grey-bg"></span><sub class="price"><?php echo $this->getFormattedPrice($data->price);?></sub>
		</p>
		</a>
		<div class="row extra">
			<div class="col-md-8 col-sm-8 col-xs-16">
				<ul class="properties">
					<?php
					/* @var $property ProductProperties */
					foreach ( $data->productProperties as $property ) {
						echo sprintf('<li>%s: %s</li>', CHtml::encode( $property->property_name), CHtml::encode( ( (int)preg_replace('/[^0-9]*/', '', $property->property_value) == 0)? '-' : $property->property_value) );
					}?>
				</ul>
			</div>
			<div class="col-md-8 col-sm-8 col-xs-16 price-large">
				<?php if (!empty($data->special_price)) { ?>
					<span class="price-special"><?php echo $this->getFormattedPrice($data->special_price);?></span>
					<span class="price-normal">&#8594; <?php echo $this->getFormattedPrice($data->price);?></span>
				<?php } ?>
			</div>
		</div>
		<div class="pull-right extra">
			<?php
			echo CHtml::link( Yii::t('app', 'Купить'), array('order/add', 'pid'=>$data->id), array('class'=>'btn btn-primary js-add-to-cart') );
			?>
		</div>
	</div>
	<!-- PRODUCT END // -->

protected/views/category/_search.php
<?php
/* @var $this CategoryController */
/* @var $model Category */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'slug'); ?>
		<?php echo $form->textArea($model,'slug',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'image'); ?>
		<?php echo $form->textField($model,'image',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'sort'); ?>
		<?php echo $form->textField($model,'sort'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated'); ?>
		<?php echo $form->textField($model,'updated'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/category/admin.php
<?php
/* @var $this CategoryController */
/* @var $model Category */

$this->breadcrumbs=array(
	'Categories'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Category', 'url'=>array('index')),
	array('label'=>'Create Category', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#category-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Categories</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'category-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'slug',
		'image',
		'sort',
		'created',
		/*
		'updated',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/category/create.php
<?php
/* @var $this CategoryController */
/* @var $model Category */

$this->breadcrumbs=array(
	'Categories'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Category', 'url'=>array('index')),
	array('label'=>'Manage Category', 'url'=>array('admin')),
);
?>

<h1>Create Category</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/category/index.php
<?php
/**
 * @var $this CategoryController
 * @var array $hitsProducts
 * @var array $newProducts ,
 */

$this->pageTitle = '';

//Хиты продаж
$this->renderPartial( '_hits', array(
	'hitsProducts' => $hitsProducts,
) );

//Новые товары
$this->renderPartial( '_new', array(
	'newProducts'  => $newProducts,
) );

protected/views/category/update.php
<?php
/* @var $this CategoryController */
/* @var $model Category */

$this->breadcrumbs=array(
	'Categories'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Category', 'url'=>array('index')),
	array('label'=>'Create Category', 'url'=>array('create')),
	array('label'=>'View Category', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Category', 'url'=>array('admin')),
);
?>

<h1>Update Category <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/category/view.php
<?php
/** @var $this CategoryController
 * @var $model Category
 * @var $dataProvider CActiveDataProvider
 */

$this->pageTitle =  mb_strtoupper(Yii::t('app', 'категория') . " / " .$model->name , 'UTF-8');
?>

<h1 class="category-title yellow text-center"><?php echo $model->name ?><a
		href="<?php echo Yii::app()->getBaseUrl( true ); ?>" class="category-close">X</a></h1>

<div style="margin-bottom: 30px;" class="ya-separator text-center col-md-10 col-md-offset-3 col-xs-12 col-xs-offset-2"><span></span></div>

<div id="category-contents">
	<?php
	$i        = 0;
	$products = $dataProvider->getData();


	foreach ( $products as $product ) {
		if ( $i % 3 == 0 ) {
			echo " <!-- row --> \n" . '<div class="row">' . "\n";
		}

		echo '  <div class="col-md-4 ' . ( ( $i % 3 == 0 ) ? 'col-md-offset-2 col-sm-offset-1' : '' ) . ' col-sm-5 col-xs-16">' . "\n";
		$this->renderPartial( '_product', array( 'data' => $product ) );
		echo '  </div>' . "\n";

		$i ++;
		if ( $i % 3 == 0 || $i == count( $products ) + 1 ) {
			echo "</div>\n<!-- row END // -->\n\n";
		}
	}

	?>
</div>
<?php
$this->widget( 'CLinkPager',
	array(
		'id' => 'pager',
		'pages' => $dataProvider->getPagination(),
		'header' => '',
		'footer' => '',
	)
);
?>